In [3]:
import pandas as pd

data={0:[1,2,3,4,5,6], 1:[7,8,9,10,11,12], 2:[13,14,15,16,17,18], 3:[19,20,21,22,23,24]}
df=pd.DataFrame(data)
df

   0   1   2   3
0  1   7  13  19
1  2   8  14  20
2  3   9  15  21
3  4  10  16  22
4  5  11  17  23
5  6  12  18  24

In [12]:
import numpy as np
data= np.random.randint(1, 21, size=(6,4))
df = pd.DataFrame(data, columns=['A','B','C','D'])
df
df.set_index('A', inplace=True)
df

     B   C   D
A
15  18  16  16
14  17  11  13
6   10  13   5
8    6   4  13
7   10   3  14
19   3  14   2

In [16]:
data=pd.DataFrame(np.random.randint(1, 21, size=(3,3)), columns=['A','B','C'], index=['X','Y','Z'])
print(data)
print(data.at['Y','B'])

    A  B   C
X  15  3   9
Y   3  3   4
Z   3  8  14
3

In [19]:
data=pd.DataFrame(np.random.randint(1, 21, size=(5,3)), columns=['A','B','C'], index=['X','Y','Z','W','V'])
data['D'] = data['A'] + data['B']

sum_rows=data.sum(axis=1)
sum_columns=data.sum(axis=0)
print("Sum of rows:\n", sum_rows)
print("Sum of columns:\n", sum_columns)

Sum of rows:
 X    45
Y    43
Z    67
W    82
V    61
dtype: int64
Sum of columns:
 A     61
B     48
C     80
D    109
dtype: int64

In [24]:
data =pd.DataFrame(np.random.randint(1, 15, size=(5,3)), columns=['A','B','C'], index=['W','X','Y','Z','V'])

data['A']['W'] = np.nan
data['B']['X'] = np.nan
data['C']['Y'] = np.nan 
data['A']['Z'] = np.nan
print("DataFrame with NaN values:\n", data)


'''data.fillna(data.mean(), inplace=True)'''
data.dropna(inplace=True)
print("DataFrame after handling NaN values:\n", data)
data

DataFrame with NaN values:
       A     B     C
W   NaN  10.0   3.0
X   3.0   NaN   2.0
Y  12.0   7.0   NaN
Z   NaN   4.0   8.0
V  10.0   7.0  11.0
DataFrame after handling NaN values:
       A    B     C
V  10.0  7.0  11.0

C:\Users\mehta\AppData\Local\Temp\ipykernel_18212\505044342.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['A']['W'] = np.nan
C:\Users\mehta\AppData\Local\Temp\ipykernel_18212\505044342.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['B']['X'] = np.nan
C:\Users\mehta\AppData\Local\Temp\ipykernel_18212\505044342.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['B']['X'] = np.nan
C:\Users\mehta\AppData\Local\Temp\ipykernel_18212\505044342.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['C']['Y'] = np.nan
C:\Users\mehta\AppData\Local\Temp\ipykernel_18212\505044342.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['C']['Y'] = np.nan

      A    B     C
V  10.0  7.0  11.0

In [25]:
data=pd.DataFrame({'catogry':[np.random.choice(['A','B','C']) for _ in range(10)],
                   'value':[np.random.randint(1, 100) for _ in range(10)]})
print("Original DataFrame:\n", data)
data_grouped=data.groupby('catogry')
print("Grouped DataFrame:\n", data_grouped.sum())
print("Mean of each group:\n", data_grouped.mean())

Original DataFrame:
   catogry  value
0       C      4
1       B      7
2       A     99
3       A     55
4       A     67
5       B     71
6       C     50
7       B     90
8       C     81
9       A     16
Grouped DataFrame:
          value
catogry
A          237
B          168
C          135
Mean of each group:
          value
catogry
A        59.25
B        56.00
C        45.00

In [27]:
data=pd.DataFrame({'product':[np.random.choice(['A','B','C']) for _ in range(10)],
                   'category':[np.random.choice(['X','Y','Z']) for _ in range(10)],
                   'sales':[np.random.randint(1, 100) for _ in range(10)]})
print("Original DataFrame:\n", data)
grouped_data=data.groupby(['category'])
total_sales=grouped_data['sales'].sum()
print("Total sales for each category:\n", total_sales)

Original DataFrame:
   product category  sales
0       B        X     58
1       A        X     66
2       B        X     40
3       C        Z     67
4       B        X     54
5       A        Y     60
6       B        X     12
7       B        X     16
8       A        X     11
9       B        X      2
Total sales for each category:
 category
X    259
Y     60
Z     67
Name: sales, dtype: int64

In [46]:

import pandas as pd
import numpy as np
data1 = pd.DataFrame({
    'sale_date': [
        pd.Timestamp('2023-01-01') +
        pd.to_timedelta(np.random.randint(0, 365), unit='D')
        for _ in range(10)
    ],
    'category': [np.random.choice(['X','Y','Z']) for _ in range(10)],
    'price': [np.random.randint(1,100) for _ in range(10)]
})
print("Original DataFrame:\n", data1)
merged_data = data1.groupby([data1['sale_date'].dt.to_period('M'), 'category'])['price'].sum().reset_index()
print("Total sales for each month and category:\n", merged_data)

Original DataFrame:
    sale_date category  price
0 2023-01-14        X     86
1 2023-08-19        Z     54
2 2023-04-26        Y     75
3 2023-06-10        X     11
4 2023-06-11        Z     77
5 2023-08-22        Y     19
6 2023-01-24        X     46
7 2023-08-28        Y     67
8 2023-01-26        Y     46
9 2023-03-04        X     65
Total sales for each month and category:
   sale_date category  price
0   2023-01        X    132
1   2023-01        Y     46
2   2023-03        X     65
3   2023-04        Y     75
4   2023-06        X     11
5   2023-06        Z     77
6   2023-08        Y     86
7   2023-08        Z     54

In [ ]:
data =pd.DataFrame({})